/**
 * Shared inline-style tokens used throughout the app.
 * Import S directly instead of receiving it as a prop.
 */

export const S = {
  app: { fontFamily: "'Segoe UI',sans-serif", minHeight: '100vh', background: '#f0f2f5' },
  login: { minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'linear-gradient(135deg,#2c5530,#1a3a1f)', padding: 20 },
  card: { background: '#fff', padding: 32, borderRadius: 12, boxShadow: '0 10px 40px rgba(0,0,0,0.3)', width: '100%', maxWidth: 420, textAlign: 'center' },
  input: { width: '100%', padding: '12px 14px', border: '2px solid #ddd', borderRadius: 6, fontSize: 15, marginBottom: 12, boxSizing: 'border-box' },
  inputSm: { width: '90px', padding: '8px', border: '1px solid #ddd', borderRadius: 4, fontSize: 14, textAlign: 'right' },
  inputEdit: { padding: '6px 10px', border: '1px solid #2c5530', borderRadius: 4, fontSize: 14, textAlign: 'right', width: '100px' },
  btn: { padding: '14px 24px', background: '#2c5530', color: '#fff', border: 'none', borderRadius: 6, fontSize: 16, fontWeight: 600, cursor: 'pointer', width: '100%' },
  btn2: { padding: '10px 20px', background: '#6c757d', color: '#fff', border: 'none', borderRadius: 6, cursor: 'pointer' },
  btnSm: { padding: '8px 12px', background: '#2c5530', color: '#fff', border: 'none', borderRadius: 4, cursor: 'pointer', fontSize: 13, textDecoration: 'none', display: 'inline-block' },
  btnDanger: { padding: '10px 20px', background: '#dc3545', color: '#fff', border: 'none', borderRadius: 6, cursor: 'pointer' },
  header: { background: '#2c5530', color: '#fff', padding: '12px 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12 },
  nav: { background: 'transparent', color: '#fff', border: '1px solid rgba(255,255,255,0.3)', padding: '8px 16px', borderRadius: 4, cursor: 'pointer', fontSize: 14 },
  main: { padding: 24, maxWidth: 1200, margin: '0 auto' },
  box: { background: '#fff', borderRadius: 8, padding: 20, boxShadow: '0 2px 8px rgba(0,0,0,0.08)', marginBottom: 16 },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(280px,1fr))', gap: 16 },
  row: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 16, marginBottom: 16 },
  label: { display: 'block', marginBottom: 6, fontWeight: 500, fontSize: 14 },
  select: { width: '100%', padding: '12px 14px', border: '2px solid #ddd', borderRadius: 6, fontSize: 15, background: '#fff' },
  svcGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(280px,1fr))', gap: 10 },
  svc: { display: 'flex', alignItems: 'center', gap: 10, padding: '12px', background: '#f8f9fa', borderRadius: 6, border: '1px solid #e0e0e0' },
  svcActive: { background: '#e8f5e9', borderColor: '#2c5530' },
  role: { padding: 20, border: '2px solid #ddd', borderRadius: 12, textAlign: 'center', cursor: 'pointer' },
  roleA: { borderColor: '#2c5530', background: '#f0f7f1' },
  tab: { padding: '10px 16px', background: '#fff', border: '1px solid #ddd', borderRadius: 4, cursor: 'pointer', fontSize: 14 },
  tabA: { borderColor: '#2c5530', background: '#f0f7f1', fontWeight: 600 },
  badge: { display: 'inline-block', padding: '4px 12px', borderRadius: 20, fontSize: 12, fontWeight: 600 },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 14 },
  th: { textAlign: 'left', padding: '10px 8px', borderBottom: '2px solid #ddd', background: '#f8f9fa', fontWeight: 600 },
  td: { padding: '8px', borderBottom: '1px solid #eee' },
  override: { background: '#fff3cd', borderColor: '#ffc107' },
  customSvc: { display: 'grid', gridTemplateColumns: '1fr 100px', gap: 8, padding: '10px', background: '#f0f7f1', borderRadius: 6, border: '1px dashed #2c5530', marginTop: 8 },
  projCmd: { background: '#e3f2fd', padding: 16, borderRadius: 8, marginTop: 16 },
  chk: { display: 'flex', alignItems: 'flex-start', gap: 10, padding: '10px 0', borderBottom: '1px solid #eee' },
};
